### ISSUE TITLE
Double check environment.yml and requirements.txt

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-usrse24-submission#6]
I free handed so I'm actually not sure if they look corrrect.

**Comment by navarroc** [comment]
Environment.yml file looks fine. Installed it using:

```
conda env create --name pyincore-usrse --file=environment.yml --solver=libmamba
```

Installed juypter and ran the notebook without issue.

**Comment by navarroc** [comment]
requirements.txt looks fine too. I was able to setup a clean environment and pip install the requirements.txt. I installed gdal and jupyter separately and then ran the notebook without issue.

**Comment by longshuicy** [comment]
> Environment.yml file looks fine. Installed it using:
> 
> ```
> conda env create --name pyincore-usrse --file=environment.yml --solver=libmamba
> ```
> 
> Installed juypter and ran the notebook without issue.

Perfect. Maybe I can also include this command in the instruction. Thanks!
