### ISSUE TITLE
README touch-ups

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-usrse24-submission#8]
- [WIKI](https://incore.ncsa.illinois.edu/wiki). This link doesnt work
- Add some screenshots
- Missing the incore client prompt user input username/password section in the "Running Jupyter notebook" section. 

TBC...

**Comment by navarroc** [comment]
For pip installation, we should probably add a section on installing GDAL that matches their system configuration. The GDAL wrapper version needs to match their system configuration (e.g. if GDAL is 3.0.4, the pip installed python wrapper install should be the same).
